### ISSUE TITLE
Creative:requestFullScreen reject reason

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#257]
It feels we may want to introduce the reason for full screen request rejection.

**Comment by gasperk** [comment]
Yes. It may come from publisher (disallows creatives to go into fullscreen) or browser (fullscreen not allowed because there wasn't a user interaction -- this is actually a problem we're going to see a lot, because postMessage loses the user interaction flag).

**Comment by graphicdeveloper** [comment]
Good point. I wonder if it should even be keep `requestFullScreen` in the spec, or if we should note that it's been removed/unavailable due to the limitations of the architecture - and leave it to publishers/players to manage any fullScreen capabilities or UI, and only inform the SIMID creative if a fullScreen change happens. Just a thought.

**Comment by andmig** [comment]
Overkill.
