### ISSUE TITLE
Make it explicit that when an ad is unloading new content/ad will play

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#421]
https://interactiveadvertisingbureau.github.io/SIMID/#workflow-complete

Could have a step 3 

The player starts playing the next ad or content.

**Comment by andmig** [comment]
I agree it may be beneficial to articulate that it is feasible for the player to move on while the ad on its past breath.

**Comment by mimidden** [comment]
SIMID group reviewed and agree to make the update

**Comment by ryanthompson591** [comment]
Great. I should have been at this meeting.

A couple questions:
Did we decide exactly how we would

**Comment by mimidden** [comment]
We wanted to defer to you on suggested edits to the spec. But overall we agreed that we can probably just add it into this version once folks have reviewed the edits rather than wait for a new release.



From: Ryan Thompson ***@***.***>
Reply-To: InteractiveAdvertisingBureau/SIMID ***@***.***>
Date: Friday, March 26, 2021 at 10:48 AM
To: InteractiveAdvertisingBureau/SIMID ***@***.***>
Cc: Mike Midden ***@***.***>, Comment ***@***.***>
Subject: Re: [InteractiveAdvertisingBureau/SIMID] Make it explicit that when an ad is unloading new content/ad will play (#421)


Great. I should have been at this meeting.

A couple questions:
Did we decide exactly how we would
